spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://47.95.254.97:3306/english_learn_web?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 47.95.254.97
server:
  port: 8080
aliyun:
  sms:
    accessKeyId: "LTAI4FxtgTG9eBLHrkBsGC4d"
    accessKeySecret: "n7PimBiLqJUsmSppr7xtd12L3y7uop"
    singnName: "商小惠"
    verifyCodeTemplate: "SMS_176914322"
mybatis:
  type-aliases-package: com.learn.web.pojo
  mapper-locations: classpath:mapper/*.xml